### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by reinefjord** [teknologkoren/flasquelistan#1]
### Användarfunktioner
- [x] Enkelt för användarna att strequa
- [x] enkel funktion för att lägga till nya citat
- [x] funktion för prislista
- [x] Möjligt att lätt redigera användares uppgifter för användarna
- [x] Bättre felmeddelanden vid HTTP 400, se även #3.

### QM-funktioner
- [x] Möjligt att lätt redigera användares uppgifter för administratörer
- [x] Funktion för att skicka ut mail till användare med saldo under x kr
- [x] Funktion för att generera en PDF med listan som kan skrivas ut (använder HTML-tabell istället.)
- [x] Enkelt sätt att lägga till användare
- [x] enkelt sätt att ändra priser för olika kategorier (oavsett om det är "streque" eller "en öl")
- [x] Kompatibelt system för citat så man kan föra över nuvarande
- [x] möjlighet till smidiga bulktransaktioner för admin
- [x] möjlighet att göra transaktioner från användarnas sidor

### Annat
- [x] CSRF-skydda AJAX-requests. Se [Flask-WTF](https://flask-wtf.readthedocs.io/en/stable/csrf.html)
- [ ] Översättning till engelska

## Icke-kritiska funktioner
- [x] Alkomätare
- [x] Möjlighet att ladda ner v-card för enskilda användare
- [ ] Push-notis när man börjar bli för nykter
- [ ] Enkelt sätt att konfigurera och "styla" hemsidan för andra föreningar/sektioner
- [ ] PWA
- [ ] Flytta ut formuläret för att lägga in ett citat till citatsidan så att det blir smidigare att lägga till dem

**Comment by Alge** [comment]
- [ ] Möjligt att lätt redigera användares uppgifter för användarna
- [ ] Möjligt att lätt redigera användares uppgifter för administratörer
- [ ] Funktion för att skicka ut mail till användare med saldo under x kr
- [ ] Funktion för att generera en PDF med listan som kan skrivas ut
