### ISSUE TITLE
Todo API

### ISSUE THREAD

**Issue by Alge** [teknologkoren/flasquelistan#21]
endpoints for:
- [ ] Edit user data
- [x] View user data
- [x] View user vcard
- [x] Add streque
- [x] Refund streque
- [x] list recent streque
- [x] make admin transaction
- [x] refund admin transaction
- [x] list transaction (for admins)
- [ ] list transactions (to view your own transactions)
- [x] show specific transaction
- [x] add quote
- [x] list quotes
- [x] show specific quote
- [ ] get random quote
